version: 3.7.0
services:
  mongo:
    image: mongo:4.4.22-focal
    container_name: mongodb
    volumes:
      - ./db/data:/data/db
      - ./db/init/init-mongo.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: chat_backend
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 123
    restart: unless-stopped
    command: mongod --auth

  # mongo-express:
  #   image: mongo-express
  #   container_name: mongo-express
  #   restart: unless-stopped
  #   ports:
  #     - "8081:8081"
  #   environment:
  #     ME_CONFIG_MONGODB_ADMINUSERNAME: root
  #     ME_CONFIG_MONGODB_ADMINPASSWORD: 123
  #     ME_CONFIG_MONGODB_URL: mongodb://root:123@mongo:27017/
  #   depends_on:
  #     - mongo
